# Generated by Django 5.1.3 on 2025-01-01 08:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='thumbnai',
            field=cloudinary.models.CloudinaryField(default='ok', max_length=255, verbose_name='blogs/'),
            preserve_default=False,
        ),
    ]
