# Generated by Django 5.1.3 on 2025-01-01 08:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_thumbnai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='thumbnai',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='blogs'),
        ),
    ]
