# Generated by Django 5.1.3 on 2025-01-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_thumbnai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='thumbnai',
            field=models.ImageField(blank=True, upload_to='blogs/'),
        ),
    ]
