# Generated by Django 5.1.3 on 2025-01-06 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_thumbnai'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='descreption',
            field=models.TextField(default='this is blog about Lorem ipsum, dolor sit amet consectetur adipisicing elit. Delectus quae temporibus vero architecto esse odit nemo omnis, quasi quam tempora rem voluptatem assumenda, neque veritatis! Ducimus sunt harum deserunt minima?'),
            preserve_default=False,
        ),
    ]
